export interface BlogPost {
  id: string;
  title: string;
  slug: string;
  excerpt: string;
  content: string;
  author: string;
  date: string;
  readTime: string;
  tags: string[];
  category: string;
  coverImage: string;
  featured?: boolean;
  /** Popularity rank from GA data. Lower = more popular. Update from GA dashboard. */
  popularRank?: number;
}

/** Calculate read time from HTML content (~200 words per minute) */
function calcReadTime(html: string): string {
  const text = html.replace(/<[^>]+>/g, ' ').replace(/\s+/g, ' ').trim();
  const words = text.split(' ').length;
  const minutes = Math.max(1, Math.round(words / 200));
  return `${minutes} min read`;
}

export const CATEGORIES = [
  { name: 'All', slug: '' },
  { name: 'AI', slug: 'ai' },
  { name: 'Frontend', slug: 'frontend' },
  { name: 'Backend', slug: 'backend' },
  { name: 'DevOps', slug: 'devops' },
  { name: 'Tutorials', slug: 'tutorials' },
  { name: 'Open Source', slug: 'open-source' },
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: '87',
    title: 'Distributed Systems Algorithms: Consensus, Replication, and Coordination at Production Scale',
    slug: 'distributed-systems-algorithms-production-guide',
    excerpt: 'How real distributed systems agree, replicate, and coordinate. Raft and Paxos consensus, leader election in etcd and Kafka, quorum reads in Cassandra, gossip in Redis Cluster, vector clocks, CRDTs, and the consistency models that determine what your system can promise.',
    category: 'backend',
    featured: true,
    content: '',
    author: 'Vishal Anand',
    date: '2026-05-02',
    readTime: '22 min read',
    tags: ['Distributed Systems', 'Consensus', 'Raft', 'Paxos', 'CAP Theorem', 'Kubernetes', 'etcd', 'Kafka', 'Cassandra'],
    coverImage: '',
  },
  {
    id: '86',
    title: 'Rate Limiting Algorithms: Token Bucket, Sliding Window, and Distributed Rate Limiters in Production',
    slug: 'rate-limiting-algorithms-production-guide',
    excerpt: 'How API gateways, edge proxies, and service meshes throttle traffic without breaking legitimate users. Token bucket vs leaky bucket, fixed and sliding windows, distributed rate limiting with Redis, Envoy and NGINX implementations, and adaptive rate limiting under attack.',
    category: 'backend',
    featured: false,
    content: '',
    author: 'Vishal Anand',
    date: '2026-05-02',
    readTime: '18 min read',
    tags: ['Rate Limiting', 'API Gateway', 'Redis', 'Envoy', 'NGINX', 'DDoS', 'Distributed Systems', 'API Security'],
    coverImage: '',
  },
  {
    id: '85',
    title: 'Caching Strategies: Cache-Aside, Write-Through, Distributed Caches, and Invalidation in Production',
    slug: 'caching-strategies-production-guide',
    excerpt: 'Every cache eventually causes an outage if you do not design it right. Cache-aside vs write-through, distributed caching with Redis and Memcached, CDN edge caching, the thundering herd, hot keys, and the invalidation strategies that hold up at scale.',
    category: 'backend',
    featured: false,
    content: '',
    author: 'Vishal Anand',
    date: '2026-05-02',
    readTime: '20 min read',
    tags: ['Caching', 'Redis', 'Memcached', 'CDN', 'Performance', 'Distributed Systems', 'Architecture', 'Backend'],
    coverImage: '',
  },
  {
    id: '84',
    title: 'Scheduling Systems: How Kubernetes, Airflow, and Distributed Schedulers Place and Run Workloads',
    slug: 'scheduling-systems-production-guide',
    excerpt: 'How real scheduling systems decide what runs where. Kubernetes scheduler internals, distributed cron, queue-based job orchestration with Airflow and Nomad, bin-packing and fairness algorithms, and the failure modes that determine whether your workloads survive node failure.',
    category: 'devops',
    featured: false,
    content: '',
    author: 'Vishal Anand',
    date: '2026-05-02',
    readTime: '20 min read',
    tags: ['Kubernetes', 'Scheduling', 'Airflow', 'Nomad', 'Distributed Systems', 'DevOps', 'Job Orchestration'],
    coverImage: '',
  },
  {
    id: '83',
    title: 'Monorepo vs Polyrepo: How to Structure Your Codebase at Scale',
    slug: 'monorepo-vs-polyrepo-codebase-structure',
    excerpt: 'Google uses a monorepo with 2 billion lines of code. Netflix uses hundreds of separate repos. Both work. Learn when each approach wins, the tooling that makes monorepos viable (Nx, Turborepo), and how to migrate without losing your mind.',
    category: 'open-source',
    featured: false,
    content: '',
    author: 'Vishal Anand',
    date: '2026-04-28',
    readTime: '13 min read',
    tags: ['Monorepo', 'Nx', 'Turborepo', 'Architecture', 'Developer Tools'],
    coverImage: '',
  },
  {
    id: '82',
    title: 'Concurrency and Parallelism: Threads, Async, and Multiprocessing in Python',
    slug: 'python-concurrency-threads-async-multiprocessing',
    excerpt: 'The GIL does not make Python single-threaded — it makes it single-core for CPU work. Learn when to use threading (I/O), asyncio (many connections), and multiprocessing (CPU), with benchmarks showing the real performance difference.',
    category: 'tutorials',
    featured: false,
    content: '',
    author: 'Vishal Anand',
    date: '2026-04-28',
    readTime: '13 min read',
    tags: ['Python', 'Concurrency', 'Asyncio', 'Threading', 'Performance'],
    coverImage: '',
  },
  {
    id: '81',
    title: 'SQL Window Functions: The Feature That Changes How You Write Queries',
    slug: 'sql-window-functions-rank-lag-running-totals',
    excerpt: 'Window functions let you calculate rankings, running totals, moving averages, and row comparisons without GROUP BY or self-joins. Learn ROW_NUMBER, RANK, LAG/LEAD, SUM OVER, and PARTITION BY with practical examples.',
    category: 'tutorials',
    featured: false,
    content: '',
    author: 'Vishal Anand',
    date: '2026-04-28',
    readTime: '13 min read',
    tags: ['SQL', 'Window Functions', 'PostgreSQL', 'Database', 'Tutorials'],
    coverImage: '',
  },
  {
    id: '80',
    title: 'Vector Databases Explained: Embeddings, Similarity Search, and When You Need One',
    slug: 'vector-databases-embeddings-similarity-search',
    excerpt: 'Vector databases power semantic search, recommendation engines, and RAG pipelines. Learn how embeddings work, the HNSW algorithm behind similarity search, chunking strategies, and when pgvector is enough vs when you need Pinecone.',
    category: 'ai',
    featured: false,
    content: '',
    author: 'Vishal Anand',
    date: '2026-04-28',
    readTime: '13 min read',
    tags: ['Vector Database', 'Embeddings', 'RAG', 'AI', 'pgvector'],
    coverImage: '',
  },
  {
    id: '79',
    title: 'Linux Commands Every Developer Should Know But Doesn\'t',
    slug: 'linux-commands-developer-debugging-guide',
    excerpt: 'You know ls and grep. But do you know awk, xargs, jq, strace, lsof, and ss? These commands turn a 2-hour debugging session into a 5-minute investigation. Real scenarios, real commands, real solutions.',
    category: 'devops',
    featured: false,
    content: '',
    author: 'Vishal Anand',
    date: '2026-04-28',
    readTime: '12 min read',
    tags: ['Linux', 'Shell', 'Debugging', 'DevOps', 'CLI'],
    coverImage: '',
  },
  {
    id: '78',
    title: 'GitHub Actions Mastery: CI/CD Pipelines That Actually Scale',
    slug: 'github-actions-ci-cd-pipelines-mastery',
    excerpt: 'Your GitHub Actions workflow takes 20 minutes and fails randomly. Learn matrix builds, reusable workflows, aggressive caching, secrets management, self-hosted runners, and monorepo strategies that cut build times by 80%.',
    category: 'devops',
    featured: false,
    content: '',
    author: 'Vishal Anand',
    date: '2026-04-28',
    readTime: '13 min read',
    tags: ['GitHub Actions', 'CI/CD', 'DevOps', 'Automation', 'Monorepo'],
    coverImage: '',
  },
  {
    id: '77',
    title: 'State Management Showdown: NgRx vs Signals vs Services in Angular',
    slug: 'angular-state-management-ngrx-signals-services',
    excerpt: 'Angular has three state management approaches and choosing wrong means either over-engineering a todo app or under-engineering an enterprise dashboard. Compare NgRx, Signals, and plain services with real examples and a decision framework.',
    category: 'frontend',
    featured: false,
    content: '',
    author: 'Vishal Anand',
    date: '2026-04-28',
    readTime: '12 min read',
    tags: ['Angular', 'NgRx', 'Signals', 'State Management', 'Frontend'],
    coverImage: '',
  },
  {
    id: '76',
    title: 'Web Authentication API: Passwordless Login with Passkeys',
    slug: 'web-authentication-passkeys-passwordless-login',
    excerpt: 'Passwords are the weakest link in security. Passkeys replace them with biometrics and device-bound credentials. Learn WebAuthn, FIDO2, and how to implement passwordless login in your web app with real code examples.',
    category: 'frontend',
    featured: false,
    content: '',
    author: 'Vishal Anand',
    date: '2026-04-28',
    readTime: '12 min read',
    tags: ['WebAuthn', 'Passkeys', 'Security', 'Authentication', 'Frontend'],
    coverImage: '',
  },
  {
    id: '75',
    title: 'Event-Driven Architecture: From Monolith Events to Kafka Streams',
    slug: 'event-driven-architecture-kafka-cqrs-guide',
    excerpt: 'Decouple your services with events instead of API calls. Learn event sourcing, CQRS, Kafka vs RabbitMQ, dead letter queues, idempotency patterns, and how to migrate from a monolith to event-driven without rewriting everything.',
    category: 'backend',
    featured: false,
    content: '',
    author: 'Vishal Anand',
    date: '2026-04-28',
    readTime: '13 min read',
    tags: ['Event-Driven', 'Kafka', 'RabbitMQ', 'CQRS', 'Architecture'],
    coverImage: '',
  },
  {
    id: '74',
    title: 'Database Connection Pooling: Why Your App Crashes at 100 Users',
    slug: 'database-connection-pooling-pgbouncer-guide',
    excerpt: 'Your app works fine in development but crashes in production with "too many connections." Learn how connection pooling works, how to configure PgBouncer, Django CONN_MAX_AGE, and SQLAlchemy pools, and the math behind sizing your pool.',
    category: 'backend',
    featured: false,
    content: '',
    author: 'Vishal Anand',
    date: '2026-04-28',
    readTime: '12 min read',
    tags: ['Database', 'PostgreSQL', 'PgBouncer', 'Django', 'Performance'],
    coverImage: '',
  },
  {
    id: '73',
    title: 'Contributing to Open Source: Your First PR in 30 Minutes',
    slug: 'contributing-open-source-first-pull-request',
    excerpt: 'Open source contribution is not just for experts. This step-by-step guide takes you from finding a beginner-friendly issue to submitting your first pull request — including the fork workflow, commit conventions, and review etiquette.',
    category: 'open-source',
    featured: false,
    content: '',
    author: 'Vishal Anand',
    date: '2026-04-28',
    readTime: '11 min read',
    tags: ['Open Source', 'Git', 'GitHub', 'Career', 'Developer Tools'],
    coverImage: '',
  },
  {
    id: '72',
    title: 'Regex Demystified: From Fear to Fluency in 20 Minutes',
    slug: 'regex-demystified-practical-patterns-guide',
    excerpt: 'Regular expressions look like line noise until you learn to read them left to right. This guide breaks down regex visually, covers the 20 patterns that solve 95% of real-world tasks, and includes a copy-paste cheat sheet.',
    category: 'tutorials',
    featured: false,
    content: '',
    author: 'Vishal Anand',
    date: '2026-04-28',
    readTime: '11 min read',
    tags: ['Regex', 'Python', 'JavaScript', 'Tutorials', 'Developer Tools'],
    coverImage: '',
  },
  {
    id: '71',
    title: 'Design Patterns That Actually Matter: 7 Patterns Every Developer Uses Daily',
    slug: 'design-patterns-strategy-observer-factory-guide',
    excerpt: 'Forget the Gang of Four book with 23 patterns you will never use. These 7 design patterns appear in every codebase, every framework, and every system design interview. Real Python and TypeScript examples, zero academic fluff.',
    category: 'tutorials',
    featured: false,
    content: '',
    author: 'Vishal Anand',
    date: '2026-04-28',
    readTime: '13 min read',
    tags: ['Design Patterns', 'Python', 'TypeScript', 'Architecture', 'Tutorials'],
    coverImage: '',
  },
  {
    id: '70',
    title: 'Fine-Tuning vs RAG vs Prompt Engineering: Which AI Strategy Do You Need?',
    slug: 'fine-tuning-vs-rag-vs-prompt-engineering',
    excerpt: 'Your AI project needs domain-specific knowledge. Should you fine-tune a model, build a RAG pipeline, or engineer better prompts? This decision matrix covers cost, accuracy, latency, maintenance, and when each approach wins.',
    category: 'ai',
    featured: false,
    content: '',
    author: 'Vishal Anand',
    date: '2026-04-28',
    readTime: '12 min read',
    tags: ['AI', 'RAG', 'Fine-Tuning', 'Prompt Engineering', 'LLM'],
    coverImage: '',
  },
  {
    id: '69',
    title: 'Observability Stack: Logs, Metrics, and Traces with OpenTelemetry',
    slug: 'observability-opentelemetry-logs-metrics-traces',
    excerpt: 'Logs tell you what happened. Metrics tell you how much. Traces tell you where time was spent. OpenTelemetry unifies all three into one instrumentation layer. Learn to build a complete observability stack from scratch.',
    category: 'devops',
    featured: false,
    content: '',
    author: 'Vishal Anand',
    date: '2026-04-28',
    readTime: '13 min read',
    tags: ['Observability', 'OpenTelemetry', 'Grafana', 'Prometheus', 'DevOps'],
    coverImage: '',
  },
  {
    id: '68',
    title: 'Terraform from Zero to Production: Infrastructure as Code That Scales',
    slug: 'terraform-infrastructure-as-code-production-guide',
    excerpt: 'Stop clicking around cloud consoles. Terraform lets you define, version, and automate your infrastructure. Learn modules, state management, workspaces, CI/CD pipelines, and the mistakes that corrupt your state file.',
    category: 'devops',
    featured: false,
    content: '',
    author: 'Vishal Anand',
    date: '2026-04-28',
    readTime: '13 min read',
    tags: ['Terraform', 'IaC', 'AWS', 'DevOps', 'CI/CD'],
    coverImage: '',
  },
  {
    id: '67',
    title: 'Micro-Frontends: Splitting a Monolith UI Without the Pain',
    slug: 'micro-frontends-module-federation-guide',
    excerpt: 'Your frontend monolith has 200 components, 15 teams, and deploys take 45 minutes. Micro-frontends let teams ship independently. Learn Module Federation, shared dependencies, routing strategies, and when NOT to use them.',
    category: 'frontend',
    featured: false,
    content: '',
    author: 'Vishal Anand',
    date: '2026-04-28',
    readTime: '12 min read',
    tags: ['Micro-Frontends', 'Module Federation', 'Webpack', 'Architecture', 'Frontend'],
    coverImage: '',
  },
  {
    id: '66',
    title: 'CSS Grid and Flexbox Mastery: Stop Guessing, Start Designing',
    slug: 'css-grid-flexbox-mastery-responsive-layouts',
    excerpt: 'Flexbox is for one-dimensional flow. Grid is for two-dimensional layout. Learn when to use which, build responsive layouts without media queries, and master the patterns that replace 90% of CSS frameworks.',
    category: 'frontend',
    featured: false,
    content: '',
    author: 'Vishal Anand',
    date: '2026-04-28',
    readTime: '11 min read',
    tags: ['CSS', 'Flexbox', 'Grid', 'Responsive Design', 'Frontend'],
    coverImage: '',
  },
  {
    id: '65',
    title: 'Celery Task Queues: From Simple Tasks to Complex Workflows',
    slug: 'celery-task-queues-django-workflows-guide',
    excerpt: 'Django + Celery is the most popular async task processing stack in Python. Learn task retries, chains, chords, rate limiting, monitoring with Flower, and the production patterns that keep your workers healthy.',
    category: 'backend',
    featured: false,
    content: '',
    author: 'Vishal Anand',
    date: '2026-04-28',
    readTime: '12 min read',
    tags: ['Celery', 'Django', 'Python', 'Task Queue', 'Redis'],
    coverImage: '',
  },
  {
    id: '64',
    title: 'OAuth 2.0 and OpenID Connect: The Developer\'s No-BS Guide',
    slug: 'oauth2-openid-connect-developer-guide',
    excerpt: 'OAuth 2.0 is not authentication. OpenID Connect is. This guide cuts through the confusion — authorization code flow, PKCE, refresh tokens, JWTs, and the security mistakes that get apps hacked.',
    category: 'backend',
    featured: false,
    content: '',
    author: 'Vishal Anand',
    date: '2026-04-28',
    readTime: '13 min read',
    tags: ['OAuth', 'OpenID Connect', 'Security', 'Authentication', 'Backend'],
    coverImage: '',
  },
  {
    id: '63',
    title: 'How to Build a Python CLI Tool That People Actually Use',
    slug: 'build-python-cli-tool-click-typer-pypi',
    excerpt: 'Build a production-quality Python CLI with Typer, publish it to PyPI, add shell completions, colored output, progress bars, and CI/CD — everything between "it works on my machine" and "10,000 installs."',
    category: 'open-source',
    featured: false,
    content: '',
    author: 'Vishal Anand',
    date: '2026-04-27',
    readTime: '12 min read',
    tags: ['Python', 'CLI', 'Open Source', 'PyPI', 'Developer Tools'],
    coverImage: '',
  },
  {
    id: '62',
    title: 'API Design Best Practices: REST, GraphQL, and gRPC Compared',
    slug: 'api-design-rest-graphql-grpc-compared',
    excerpt: 'REST is not always the answer. Learn when REST, GraphQL, and gRPC each shine — with real schema examples, performance benchmarks, versioning strategies, and a decision framework for choosing the right protocol.',
    category: 'backend',
    featured: false,
    content: '',
    author: 'Vishal Anand',
    date: '2026-04-27',
    readTime: '13 min read',
    tags: ['API Design', 'REST', 'GraphQL', 'gRPC', 'Backend'],
    coverImage: '',
  },
  {
    id: '61',
    title: 'Git Internals: How Git Actually Works Under the Hood',
    slug: 'git-internals-how-git-works-under-hood',
    excerpt: 'Git is not magic — it is a content-addressable object database with refs, an index, reflogs, and a graph of snapshots. Explore blobs, trees, commits, tags, branches, rebases, packfiles, and recovery.',
    category: 'tutorials',
    featured: false,
    content: '',
    author: 'Vishal Anand',
    date: '2026-04-27',
    readTime: '17 min read',
    tags: ['Git', 'Version Control', 'Tutorials', 'Developer Tools', 'Internals'],
    coverImage: '',
  },
  {
    id: '60',
    title: 'Building AI Agents with Claude: From Chatbot to Autonomous Worker',
    slug: 'building-ai-agents-claude-autonomous-worker',
    excerpt: 'Transform a simple chatbot into an autonomous agent that uses tools, maintains memory, recovers from errors, and orchestrates multi-step workflows. Practical Python guide using Claude API with production-ready patterns.',
    category: 'ai',
    featured: true,
    content: '',
    author: 'Vishal Anand',
    date: '2026-04-27',
    readTime: '14 min read',
    tags: ['AI', 'Claude', 'Agents', 'Python', 'LLM'],
    coverImage: '',
  },
  {
    id: '59',
    title: 'Kubernetes Debugging Toolkit: From kubectl to Victory',
    slug: 'kubernetes-debugging-toolkit-kubectl-guide',
    excerpt: 'Pod stuck in CrashLoopBackOff? Service not routing traffic? Node running out of memory? This is your battlefield guide to debugging Kubernetes — real commands, real scenarios, real fixes.',
    category: 'devops',
    featured: false,
    content: '',
    author: 'Vishal Anand',
    date: '2026-04-27',
    readTime: '13 min read',
    tags: ['Kubernetes', 'DevOps', 'Debugging', 'kubectl', 'Containers'],
    coverImage: '',
  },
  {
    id: '58',
    title: 'Web Performance Secrets: Core Web Vitals from Red to Green',
    slug: 'web-performance-core-web-vitals-optimization',
    excerpt: 'Your Lighthouse score is red. Users are bouncing. Google is penalizing your rankings. This guide fixes LCP, CLS, and INP with practical techniques — lazy loading, image optimization, font strategies, and real before-after audits.',
    category: 'frontend',
    featured: false,
    content: '',
    author: 'Vishal Anand',
    date: '2026-04-27',
    readTime: '12 min read',
    tags: ['Web Performance', 'Core Web Vitals', 'Angular', 'SEO', 'Frontend'],
    coverImage: '',
  },
  {
    id: '57',
    title: 'Angular Signals Deep Dive: Replacing RxJS the Right Way',
    slug: 'angular-signals-deep-dive-replacing-rxjs',
    excerpt: 'Angular Signals are not a drop-in replacement for RxJS — they solve different problems. Learn when to use signals vs observables, migration patterns, computed/effect gotchas, and real refactoring examples in Angular 21.',
    category: 'frontend',
    featured: false,
    content: '',
    author: 'Vishal Anand',
    date: '2026-04-27',
    readTime: '12 min read',
    tags: ['Angular', 'Signals', 'RxJS', 'TypeScript', 'Frontend'],
    coverImage: '',
  },
  {
    id: '56',
    title: 'Database Migrations Without Downtime: Zero-Downtime Schema Changes',
    slug: 'zero-downtime-database-migrations-expand-contract',
    excerpt: 'Adding a NOT NULL column to a 50-million-row table should not take your app offline. Learn the expand-contract pattern, online DDL, backward-compatible migrations, and the exact steps for safe schema changes in production.',
    category: 'backend',
    featured: false,
    content: '',
    author: 'Vishal Anand',
    date: '2026-04-27',
    readTime: '11 min read',
    tags: ['Database', 'PostgreSQL', 'Django', 'Migrations', 'DevOps'],
    coverImage: '',
  },
  {
    id: '55',
    title: 'Rate Limiting Algorithms Explained: Token Bucket, Sliding Window, and Leaky Bucket',
    slug: 'rate-limiting-algorithms-token-bucket-sliding-window',
    excerpt: 'Implement three production rate limiting algorithms from scratch in Python — token bucket, sliding window log, and leaky bucket. Understand the tradeoffs and pick the right one for your API.',
    category: 'backend',
    featured: false,
    content: '',
    author: 'Vishal Anand',
    date: '2026-04-27',
    readTime: '11 min read',
    tags: ['Rate Limiting', 'Python', 'Redis', 'API Design', 'Backend'],
    coverImage: '',
  },
  {
    id: '54',
    title: 'System Design in 30 Minutes: From Load Balancer to Database',
    slug: 'system-design-load-balancer-to-database',
    excerpt: 'A complete walkthrough of every layer in a scalable system — DNS, CDN, load balancers, API gateways, caching, message queues, and databases. Includes a URL shortener design exercise with back-of-envelope math.',
    category: 'tutorials',
    featured: false,
    content: '',
    author: 'Vishal Anand',
    date: '2026-04-27',
    readTime: '14 min read',
    tags: ['System Design', 'Architecture', 'Scalability', 'Interview Prep', 'Backend'],
    coverImage: '',
  },
  {
    id: '53',
    title: 'Prompt Engineering Patterns for Developers: Beyond Basic Prompts',
    slug: 'prompt-engineering-patterns-developers-guide',
    excerpt: 'Stop guessing with prompts. Learn 8 battle-tested prompt engineering patterns used in production AI systems — chain-of-thought, few-shot, structured output, guardrails, RAG, and tool use — with real Python code using the Anthropic SDK.',
    category: 'ai',
    featured: true,
    content: '',
    author: 'Vishal Anand',
    date: '2026-04-27',
    readTime: '13 min read',
    tags: ['AI', 'Prompt Engineering', 'Claude', 'LLM', 'Developer Tools'],
    coverImage: '',
  },
  {
    id: '52',
    title: 'Docker Multi-Stage Builds: Shrink Your Images by 90%',
    slug: 'docker-multi-stage-builds-shrink-images',
    excerpt: 'Your Docker images are bloated with build tools, dev dependencies, and source code that has no business in production. Multi-stage builds can shrink a 1.2GB image to 45MB. Here is exactly how to do it for Node.js, Python, Go, and Java.',
    category: 'devops',
    featured: false,
    content: '',
    author: 'Vishal Anand',
    date: '2026-04-27',
    readTime: '10 min read',
    tags: ['Docker', 'DevOps', 'Containers', 'CI/CD', 'Performance'],
    coverImage: '',
  },
  {
    id: '51',
    title: 'WebSocket vs SSE vs Long Polling: Building Real-Time Features the Right Way',
    slug: 'websocket-sse-long-polling-realtime-guide',
    excerpt: 'Not every real-time feature needs WebSocket. Learn when to use Server-Sent Events, Long Polling, or WebSocket with practical Angular examples, scaling strategies, and a decision framework that saves you from over-engineering.',
    category: 'frontend',
    featured: false,
    content: '',
    author: 'Vishal Anand',
    date: '2026-04-27',
    readTime: '11 min read',
    tags: ['WebSocket', 'SSE', 'Real-Time', 'Angular', 'JavaScript'],
    coverImage: '',
  },
  {
    id: '50',
    title: 'Database Indexing Secrets: Why Your Queries Are Slow and How to Fix Them',
    slug: 'database-indexing-secrets-slow-queries-fix',
    excerpt: 'Your database has indexes but queries are still slow. Learn how B-tree internals, composite index ordering, covering indexes, and EXPLAIN ANALYZE can transform query performance from seconds to milliseconds.',
    category: 'backend',
    featured: false,
    content: '',
    author: 'Vishal Anand',
    date: '2026-04-27',
    readTime: '12 min read',
    tags: ['Database', 'PostgreSQL', 'MySQL', 'Performance', 'SQL'],
    coverImage: '',
  },
  {
    id: '49',
    title: 'How Claude Tokens Actually Work: The Complete Transparency Guide',
    slug: 'claude-tokens-hidden-costs-optimization-guide',
    excerpt: 'Every Claude API call has hidden token costs you never see — system prompts, tool definitions, thinking tokens, MCP schemas, and CLAUDE.md. This guide exposes every hidden data point and shows exactly how to minimize your token spend.',
    category: 'ai',
    featured: true,
    content: '',
    author: 'Vishal Anand',
    date: '2026-04-25',
    readTime: '12 min read',
    tags: ['Claude', 'AI', 'Tokens', 'API', 'Cost Optimization', 'Anthropic', 'LLM'],
    coverImage: '',
    popularRank: 2,
  },
  {
    id: '48',
    title: 'OKRs for Engineers: A Practical Guide with Real-World Examples',
    slug: 'okr-objectives-key-results-practical-guide',
    excerpt: 'Learn how to write effective OKRs that actually drive results. This guide breaks down the OKR framework with real examples from engineering, product, DevOps, and startup teams — no corporate jargon.',
    category: 'tutorials',
    featured: false,
    content: '',
    author: 'Vishal Anand',
    date: '2026-04-23',
    readTime: '10 min read',
    tags: ['OKR', 'Engineering Management', 'Goal Setting', 'Team Management', 'Productivity', 'Startups'],
    coverImage: '',
    popularRank: 5,
  },
  {
    id: '47',
    title: 'CAP Theorem Explained: The Trade-Off Every Distributed System Must Make',
    slug: 'cap-theorem-distributed-systems-explained',
    excerpt: 'Understand the CAP theorem from first principles. Learn why distributed databases must choose between consistency and availability during network partitions, with real-world examples from MongoDB, Cassandra, DynamoDB, and PostgreSQL.',
    category: 'backend',
    featured: false,
    content: '',
    author: 'Vishal Anand',
    date: '2026-04-23',
    readTime: '12 min read',
    tags: ['CAP Theorem', 'Distributed Systems', 'System Design', 'Database', 'Consistency', 'Availability'],
    coverImage: '',
    popularRank: 3,
  },
  {
    id: '46',
    title: 'Claude Design: Anthropic\'s AI Design Tool That Turns Prompts into Prototypes',
    slug: 'claude-design-ai-design-tool-guide',
    excerpt: 'Claude Design lets you create polished prototypes, pitch decks, and landing pages through conversation. Learn what it is, how to use it, pricing, Canva integration, Claude Code handoff, and how it compares to Figma.',
    category: 'ai',
    featured: true,
    content: '',
    author: 'Vishal Anand',
    date: '2026-04-22',
    readTime: '8 min read',
    tags: ['Claude', 'AI', 'Design Tools', 'Anthropic', 'Prototyping', 'Figma', 'Canva'],
    coverImage: '/images/banners/claude-design-ai-design-tool-guide.svg',
    popularRank: 1,
  },
  {
    id: '45',
    title: 'Multi-Tenant and Multi-Domain Architecture: The Complete Guide for SaaS Engineers',
    slug: 'multi-tenant-multi-domain-architecture-guide',
    excerpt: 'Understand the real trade-offs of multi-tenancy — shared database vs schema-per-tenant vs database-per-tenant. Learn multi-domain routing, tenant isolation, data partitioning, and how companies like Slack, Shopify, and Atlassian actually do it.',
    category: 'backend',
    featured: true,
    content: '',
    author: 'Coder Secret',
    date: '2026-04-19',
    readTime: '26 min read',
    tags: ['Multi-Tenant', 'Architecture', 'SaaS', 'Database', 'Backend'],
    coverImage: '',
  },
  {
    id: '43',
    title: 'Envoy Proxy and xDS: The Dynamic Control Plane for Modern Infrastructure',
    slug: 'envoy-proxy-xds-server-guide',
    excerpt: 'Understand Envoy proxy from the ground up — listeners, clusters, routes — then build a dynamic control plane with xDS. Learn why every service mesh (Istio, Linkerd, Consul) is built on Envoy.',
    category: 'devops',
    content: '',
    author: 'Coder Secret',
    date: '2026-04-19',
    readTime: '22 min read',
    tags: ['Envoy', 'xDS', 'Service Mesh', 'DevOps', 'Proxy'],
    coverImage: '',
  },
  {
    id: '44',
    title: 'GreptimeDB + Grafana: Build a Modern Observability Stack from Scratch',
    slug: 'greptimedb-grafana-observability-tutorial',
    excerpt: 'Set up GreptimeDB as your time-series database and connect it to Grafana for real-time dashboards. A practical tutorial covering installation, data ingestion, PromQL queries, and production dashboards.',
    category: 'devops',
    content: '',
    author: 'Coder Secret',
    date: '2026-04-19',
    readTime: '20 min read',
    tags: ['GreptimeDB', 'Grafana', 'Observability', 'Prometheus', 'Time Series'],
    coverImage: '',
  },
  {
    id: '42',
    title: 'Delta Lake, Apache Iceberg, and S3 Tables: A Beginner-Friendly Guide to Modern Table Formats',
    slug: 'delta-lake-iceberg-s3-tables-beginner-guide',
    excerpt: 'You keep hearing about Delta Lake, Iceberg, and Hudi but have no clue what they actually do. This guide starts from "what even is a table format?" and builds up to understanding why the entire data industry is moving to these formats.',
    category: 'backend',
    content: '',
    author: 'Coder Secret',
    date: '2026-04-19',
    readTime: '26 min read',
    tags: ['Delta Lake', 'Iceberg', 'Data Engineering', 'S3 Tables', 'Lakehouse'],
    coverImage: '',
  },
  {
    id: '41',
    title: 'Metastore Explained: Hive, AWS Glue, Databricks Unity Catalog, and Why You Need One',
    slug: 'metastore-hive-glue-unity-catalog-guide',
    excerpt: 'Why does a data lake need a metastore? Start from the problem, understand Hive Metastore, AWS Glue Data Catalog, Databricks Unity Catalog, and Apache Polaris. Learn when to use each with architecture diagrams and real examples.',
    category: 'backend',
    content: '',
    author: 'Coder Secret',
    date: '2026-04-19',
    readTime: '24 min read',
    tags: ['Metastore', 'Hive', 'AWS Glue', 'Data Engineering', 'Iceberg'],
    coverImage: '',
  },
  {
    id: '40',
    title: 'Cloud IAM Demystified: AWS, GCP, and Azure Identity Management Compared',
    slug: 'cloud-iam-aws-gcp-azure-compared',
    excerpt: 'A practical guide to Cloud IAM across AWS, GCP, and Azure. Learn the terminology mapping, see real policy examples, and understand the right approach for production — no matter which cloud you use.',
    category: 'devops',
    content: '',
    author: 'Coder Secret',
    date: '2026-04-19',
    readTime: '25 min read',
    tags: ['IAM', 'AWS', 'GCP', 'Azure', 'Cloud Security'],
    coverImage: '',
  },
  {
    id: '39',
    title: 'M2M Authentication in Go: m2mauth, SPIFFE, and SPIRE for Production Workloads',
    slug: 'm2m-authentication-golang-m2mauth-library',
    excerpt: 'Implement M2M authentication in Go using the m2mauth library, then scale to production with SPIFFE and SPIRE for automatic identity management. Covers mTLS, SVIDs, workload attestation, and Kubernetes deployment.',
    category: 'backend',
    content: '',
    author: 'Coder Secret',
    date: '2026-04-18',
    readTime: '22 min read',
    tags: ['Go', 'mTLS', 'SPIFFE', 'SPIRE', 'Security'],
    coverImage: '',
  },
  {
    id: '38',
    title: 'Claude Code Prompting Guide: Build Better Software 10x Faster',
    slug: 'claude-code-prompting-guide-build-faster',
    excerpt: 'Master the art of prompting Claude Code. Learn the patterns, structures, and techniques that turn vague instructions into production-grade code — with real before/after examples from building this very blog.',
    category: 'ai',
    content: '',
    author: 'Coder Secret',
    date: '2026-04-18',
    readTime: '20 min read',
    tags: ['Claude Code', 'AI', 'Productivity', 'Tutorial', 'Prompting'],
    coverImage: '',
  },
  {
    id: '37',
    title: 'Building Your Own Design System: The Complete Practical Guide',
    slug: 'build-your-own-design-system-guide',
    excerpt: 'A no-nonsense, production-grade guide to building a design system from scratch. Covers design tokens, component architecture, documentation, versioning, and the mistakes that kill most design systems before they launch.',
    category: 'frontend',
    content: '',
    author: 'Coder Secret',
    date: '2026-04-18',
    readTime: '28 min read',
    tags: ['Design System', 'Frontend', 'CSS', 'Architecture', 'UI'],
    coverImage: '',
  },
  {
    id: '35',
    title: 'How a CPU Actually Works: Architecture Explained for Software Engineers',
    slug: 'cpu-architecture-explained-for-developers',
    excerpt: 'Understand what happens inside the CPU when your code runs — the fetch-decode-execute cycle, pipelining, branch prediction, out-of-order execution, and why your single-threaded Python code uses only 1 of 16 cores.',
    category: 'backend',
    content: '',
    author: 'Coder Secret',
    date: '2026-04-11',
    readTime: '18 min read',
    tags: ['CPU', 'Architecture', 'Performance', 'SIMD', 'Backend'],
    coverImage: '',
  },
  {
    id: '36',
    title: 'x86 vs ARM: The Architecture War That Shapes Every Device You Own',
    slug: 'x86-vs-arm-architecture-comparison',
    excerpt: 'Understand the real differences between x86 (Intel/AMD) and ARM (Apple Silicon, Snapdragon, Graviton) — CISC vs RISC, power efficiency, performance, and why ARM is winning the future of computing.',
    category: 'backend',
    content: '',
    author: 'Coder Secret',
    date: '2026-04-11',
    readTime: '16 min read',
    tags: ['x86', 'ARM', 'CPU', 'Architecture', 'Cloud'],
    coverImage: '',
  },
  {
    id: '34',
    title: 'CPU Cache Layers Explained: Why Your Code Is Slower Than You Think',
    slug: 'cpu-cache-layers-l1-l2-l3-practical-guide',
    excerpt: 'An honest, practical walkthrough of CPU cache — L1, L2, L3 layers, cache lines, and why that innocent 2D array iteration is destroying your performance. Real benchmarks in C and Python included.',
    category: 'backend',
    content: '',
    author: 'Coder Secret',
    date: '2026-04-11',
    readTime: '22 min read',
    tags: ['CPU', 'Performance', 'Cache', 'C', 'Optimization'],
    coverImage: '',
  },
  {
    id: '33',
    title: 'Firebase Realtime Database: The Practical Guide with Real Project Examples',
    slug: 'firebase-realtime-database-tutorial',
    excerpt: 'Learn Firebase Realtime Database from scratch — setup, CRUD operations, real-time listeners, security rules. Includes a complete chat app build, plus honest coverage of limitations you need to know before committing to Firebase.',
    category: 'tutorials',
    content: '',
    author: 'Coder Secret',
    date: '2026-04-10',
    readTime: '20 min read',
    tags: ['Firebase', 'Realtime Database', 'JavaScript', 'Python', 'Tutorial'],
    coverImage: '',
  },
  {
    id: '32',
    title: 'Build Software for Windows: A Practical Guide with Python Tutorial',
    slug: 'build-windows-software-python-tutorial',
    excerpt: 'Learn how to build real Windows applications — from language selection to packaging and distribution. Includes a hands-on Python project: build a desktop file organizer app with GUI, then package it as a standalone .exe.',
    category: 'tutorials',
    content: '',
    author: 'Coder Secret',
    date: '2026-04-10',
    readTime: '18 min read',
    tags: ['Windows', 'Python', 'Desktop', 'tkinter', 'Tutorial'],
    coverImage: '',
  },
  {
    id: '31',
    title: 'Build a Local AI App Stack: RAG, Function Calling, and Agents Without Cloud APIs',
    slug: 'local-ai-app-rag-agents-no-cloud',
    excerpt: 'Go beyond chatting with a local LLM. Build real AI applications — RAG for document Q&A, function calling for tool use, and autonomous agents — all running 100% locally with zero API costs.',
    category: 'ai',
    content: '',
    author: 'Coder Secret',
    date: '2026-04-09',
    readTime: '22 min read',
    tags: ['RAG', 'AI Agents', 'LangChain', 'Ollama', 'Tutorial'],
    coverImage: '',
  },
  {
    id: '30',
    title: 'Run Google Gemma 4 Locally: Complete Setup Guide for Windows, macOS, and Linux',
    slug: 'run-gemma-4-locally-windows-macos-linux',
    excerpt: 'Step-by-step guide to running Google Gemma 4 on your own machine using Ollama, llama.cpp, and Hugging Face Transformers. Covers hardware requirements, quantization, GPU acceleration, and practical usage.',
    category: 'ai',
    content: '',
    author: 'Coder Secret',
    date: '2026-04-09',
    readTime: '18 min read',
    tags: ['Gemma', 'LLM', 'AI', 'Ollama', 'Tutorial'],
    coverImage: '',
  },
  {
    id: '29',
    title: 'How Hackers Attack Your API: A Developer\'s Defense Guide',
    slug: 'api-security-attacks-defense-guide',
    excerpt: 'Learn the top 10 ways hackers exploit APIs — SQL injection, XSS, broken auth, rate limit bypass, CORS misconfiguration — and how to defend against each one with real code examples.',
    category: 'backend',
    content: '',
    author: 'Coder Secret',
    date: '2026-04-08',
    readTime: '20 min read',
    tags: ['API Security', 'OWASP', 'SQL Injection', 'XSS', 'Rate Limiting'],
    coverImage: '',
  },
  {
    id: '27',
    title: 'SOLID Principles in Practice: Write Code That Doesn\'t Rot',
    slug: 'solid-principles-practical-examples',
    excerpt: 'Learn the 5 SOLID principles through real-world Python and TypeScript examples. See bad code, understand why it breaks, then refactor it into clean, maintainable architecture.',
    category: 'tutorials',
    content: '',
    author: 'Coder Secret',
    date: '2026-04-08',
    readTime: '18 min read',
    tags: ['SOLID', 'Design Patterns', 'Python', 'Clean Code', 'Tutorial'],
    coverImage: '',
  },
  {
    id: '28',
    title: 'Separation of Concerns: The Architecture Principle Behind Every Clean Codebase',
    slug: 'separation-of-concerns-architecture-guide',
    excerpt: 'Understand why mixing business logic with database queries and HTTP handling creates unmaintainable code. Learn SoC through layered architecture, MVC, microservices, and frontend patterns — with real refactoring examples.',
    category: 'backend',
    content: '',
    author: 'Coder Secret',
    date: '2026-04-08',
    readTime: '16 min read',
    tags: ['Architecture', 'Clean Code', 'Design Patterns', 'SoC', 'Backend'],
    coverImage: '',
  },
  {
    id: '26',
    title: 'Compression Algorithms Explained: From Gzip to Zstd with Real Benchmarks',
    slug: 'compression-algorithms-benchmarks-guide',
    excerpt: 'Understand how compression works, compare every major algorithm (gzip, brotli, zstd, lz4, snappy, bzip2, xz), and see real benchmarks. Learn exactly which one to use for your specific use case.',
    category: 'backend',
    content: '',
    author: 'Coder Secret',
    date: '2026-04-08',
    readTime: '20 min read',
    tags: ['Compression', 'Performance', 'Backend', 'Algorithms', 'Benchmarks'],
    coverImage: '',
  },
  {
    id: '25',
    title: 'Kubernetes Networking Made Simple: Services, Ingress, and Load Balancers Explained',
    slug: 'kubernetes-networking-services-ingress-load-balancer',
    excerpt: 'Confused by ClusterIP, NodePort, LoadBalancer, Ingress, and ALB Controller? This beginner-friendly guide explains when to use each Kubernetes networking option — with real analogies, diagrams, and practical examples.',
    category: 'devops',
    content: '',
    author: 'Coder Secret',
    date: '2026-04-08',
    readTime: '22 min read',
    tags: ['Kubernetes', 'Networking', 'Ingress', 'AWS', 'DevOps'],
    coverImage: '',
  },
  {
    id: '24',
    title: 'Encryption, Hashing, and Cryptography: The Complete Practical Guide',
    slug: 'encryption-hashing-cryptography-practical-guide',
    excerpt: 'Understand symmetric vs asymmetric encryption, hashing algorithms, digital signatures, and real-world usage — with Python code for every concept. Know exactly when to use AES, RSA, SHA-256, bcrypt, or HMAC.',
    category: 'tutorials',
    content: '',
    author: 'Coder Secret',
    date: '2026-04-07',
    readTime: '22 min read',
    tags: ['Encryption', 'Cryptography', 'Hashing', 'Security', 'Python'],
    coverImage: '',
  },
  {
    id: '23',
    title: 'Software Compliance Demystified: HIPAA, SOC 2, PCI-DSS, GDPR, and ISO 27001',
    slug: 'software-compliance-hipaa-soc2-pci-gdpr-guide',
    excerpt: 'A developer-friendly guide to the compliance frameworks that matter. Learn what HIPAA, SOC 2, PCI-DSS, GDPR, and ISO 27001 actually require from your code, infrastructure, and team — with practical checklists.',
    category: 'backend',
    content: '',
    author: 'Coder Secret',
    date: '2026-04-07',
    readTime: '22 min read',
    tags: ['Compliance', 'HIPAA', 'SOC 2', 'GDPR', 'Security'],
    coverImage: '',
  },
  {
    id: '22',
    title: 'Master Network Layers: A Practical Guide with Real-World Debugging',
    slug: 'network-layers-practical-mastery-guide',
    excerpt: 'Stop memorizing the OSI model — start understanding it. Learn each network layer through real tools, packet captures, and debugging scenarios you will actually face in production.',
    category: 'tutorials',
    content: '',
    author: 'Coder Secret',
    date: '2026-04-07',
    readTime: '24 min read',
    tags: ['Networking', 'TCP/IP', 'DNS', 'Debugging', 'Tutorial'],
    coverImage: '',
  },
  {
    id: '21',
    title: 'Mutual TLS (mTLS) with X.509 Certificates: A Complete Python Tutorial',
    slug: 'mtls-x509-certificates-python-tutorial',
    excerpt: 'Build a complete mTLS setup from scratch — generate your own Certificate Authority, issue X.509 certificates, and implement mutual TLS authentication in Python with Flask and requests.',
    category: 'tutorials',
    content: '',
    author: 'Coder Secret',
    date: '2026-04-07',
    readTime: '24 min read',
    tags: ['mTLS', 'Security', 'X.509', 'Python', 'Certificates'],
    coverImage: '',
  },
  {
    id: '20',
    title: 'Python Threading vs Multiprocessing: A Beginner-Friendly Deep Dive',
    slug: 'python-threading-vs-multiprocessing-tutorial',
    excerpt: 'Understand the GIL, threading, multiprocessing, and asyncio in Python. Learn which concurrency model to use for your workload — with visual diagrams, real benchmarks, and practical examples.',
    category: 'backend',
    content: '',
    author: 'Coder Secret',
    date: '2026-04-06',
    readTime: '20 min read',
    tags: ['Python', 'Threading', 'Multiprocessing', 'Concurrency', 'Tutorial'],
    coverImage: '',
  },
  {
    id: '19',
    title: 'Karpenter: Intelligent Kubernetes Autoscaling That Actually Works',
    slug: 'kubernetes-karpenter-autoscaling-tutorial',
    excerpt: 'A hands-on tutorial on Karpenter — the next-generation Kubernetes node autoscaler. Learn how it replaces Cluster Autoscaler, provisions the right nodes in seconds, and cuts your cloud bill by 60%.',
    category: 'devops',
    content: '',
    author: 'Coder Secret',
    date: '2026-04-06',
    readTime: '22 min read',
    tags: ['Kubernetes', 'Karpenter', 'AWS', 'DevOps', 'Autoscaling'],
    coverImage: '',
  },
  {
    id: '17',
    title: 'gRPC: The High-Performance RPC Framework Every Backend Developer Should Know',
    slug: 'grpc-high-performance-rpc-tutorial',
    popularRank: 5,
    excerpt: 'A practical guide to gRPC — protocol buffers, service definitions, streaming, interceptors, and why gRPC is 10x faster than REST for service-to-service communication.',
    category: 'backend',
    content: '',
    author: 'Coder Secret',
    date: '2026-04-06',
    readTime: '18 min read',
    tags: ['gRPC', 'Protobuf', 'Microservices', 'Backend', 'Performance'],
    coverImage: '',
  },
  {
    id: '18',
    title: 'Apache Thrift: Cross-Language RPC Made Simple',
    slug: 'apache-thrift-cross-language-rpc',
    excerpt: 'Learn Apache Thrift — Facebook-born RPC framework for building cross-language services. Define once in Thrift IDL, generate clients in Python, Java, Go, C++, and 20+ languages.',
    category: 'backend',
    content: '',
    author: 'Coder Secret',
    date: '2026-04-06',
    readTime: '16 min read',
    tags: ['Thrift', 'RPC', 'Microservices', 'Backend', 'Cross-Language'],
    coverImage: '',
  },
  {
    id: '16',
    title: 'Apache Arrow: The Universal Columnar Format Powering Modern Data',
    slug: 'apache-arrow-columnar-format-tutorial',
    excerpt: 'A deep dive into Apache Arrow — the in-memory columnar format that eliminates serialization overhead. Learn how it works, why it makes data processing 10-100x faster, and how to use it in Python, Rust, and across systems.',
    category: 'backend',
    content: '',
    author: 'Coder Secret',
    date: '2026-04-06',
    readTime: '22 min read',
    tags: ['Apache Arrow', 'Data Engineering', 'Python', 'Performance', 'Columnar'],
    coverImage: '',
  },
  {
    id: '15',
    title: 'MCP Servers: The Universal Plugin System for AI Agents',
    slug: 'mcp-servers-ai-agents-tutorial',
    excerpt: 'Learn what the Model Context Protocol (MCP) is, why it matters for AI development, and how to build your own MCP server that gives AI agents access to any tool or data source.',
    category: 'ai',
    content: '',
    author: 'Coder Secret',
    date: '2026-04-06',
    readTime: '20 min read',
    tags: ['MCP', 'AI', 'Claude', 'Tutorial', 'Python'],
    coverImage: '',
  },
  {
    id: '14',
    title: 'Ethical Hacking for Beginners: A Hands-On Tutorial',
    slug: 'ethical-hacking-beginners-tutorial',
    popularRank: 1,
    excerpt: 'Learn ethical hacking from scratch — reconnaissance, scanning, exploitation, and reporting. A beginner-friendly, hands-on guide with real tools, safe labs, and responsible disclosure practices.',
    category: 'tutorials',
    content: '',
    author: 'Coder Secret',
    date: '2026-04-05',
    readTime: '25 min read',
    tags: ['Ethical Hacking', 'Security', 'Penetration Testing', 'Tutorial', 'Cybersecurity'],
    coverImage: '',
  },
  {
    id: '13',
    title: 'Angular 21 in 2026: Why It Wins for Large-Scale Applications',
    slug: 'angular-21-large-scale-applications-comparison',
    excerpt: 'A deep dive into Angular 21 — signals, standalone components, deferred views, and why Angular dominates enterprise-scale apps. Compared head-to-head with React and Vue.',
    category: 'frontend',
    content: '',
    author: 'Coder Secret',
    date: '2026-04-04',
    readTime: '20 min read',
    tags: ['Angular', 'React', 'Vue', 'Frontend', 'Performance'],
    coverImage: '',
  },
  {
    id: '12',
    title: 'Python C Extensions Workshop: Build Your First High-Performance Module',
    slug: 'python-c-extensions-workshop',
    excerpt: 'A practical, hands-on workshop for writing CPython C extensions. Go from zero to a production-quality C module with proper memory management, error handling, and packaging.',
    category: 'tutorials',
    content: '',
    author: 'Coder Secret',
    date: '2026-04-04',
    readTime: '22 min read',
    tags: ['Python', 'C Extension', 'Performance', 'Tutorial', 'Workshop'],
    coverImage: '',
  },
  {
    id: '11',
    title: 'SCIM Explained: Automate User Provisioning Across Your SaaS Apps',
    slug: 'scim-user-provisioning-tutorial',
    excerpt: 'A hands-on tutorial on SCIM (System for Cross-domain Identity Management) — what it is, why enterprises need it, and how to implement a SCIM server from scratch.',
    category: 'tutorials',
    content: '',
    author: 'Coder Secret',
    date: '2026-04-04',
    readTime: '16 min read',
    tags: ['SCIM', 'Identity', 'Provisioning', 'Tutorial', 'Enterprise'],
    coverImage: '',
  },
  {
    id: '10',
    title: 'Headless APIs vs Programmatic APIs: What They Are and When to Use Each',
    slug: 'headless-api-vs-programmatic-api',
    excerpt: 'Understand the difference between headless APIs and programmatic APIs, how they work under the hood, and when to choose one over the other for your architecture.',
    category: 'backend',
    content: '',
    author: 'Coder Secret',
    date: '2026-04-04',
    readTime: '14 min read',
    tags: ['API Design', 'Headless', 'Backend', 'Architecture', 'REST'],
    coverImage: '',
  },
  {
    id: '9',
    title: 'Kubernetes Operators: Build Your Own Operator Using Golang',
    slug: 'kubernetes-operators-build-your-own-with-golang',
    popularRank: 6,
    excerpt: 'Learn what Kubernetes Operators are, why they matter, and how to build your own custom operator from scratch using Golang and the Operator SDK.',
    category: 'devops',
    content: '',
    author: 'Coder Secret',
    date: '2026-04-04',
    readTime: '15 min read',
    tags: ['Kubernetes', 'Golang', 'DevOps', 'Operators', 'Cloud Native'],
    coverImage: '',
  },
  {
    id: '8',
    title: 'Improving Python Code Performance: Practical Tips That Actually Work',
    slug: 'improving-python-code-performance',
    popularRank: 4,
    excerpt: 'From profiling bottlenecks to leveraging built-in optimizations, learn proven techniques to make your Python code run significantly faster.',
    category: 'backend',
    content: '',
    author: 'Coder Secret',
    date: '2026-04-04',
    readTime: '18 min read',
    tags: ['Python', 'Performance', 'Numba', 'Cython', 'C Extensions'],
    coverImage: '',
  },
  {
    id: '7',
    title: 'M2M Authentication: Securing Service-to-Service Communication',
    slug: 'm2m-authentication-service-to-service',
    excerpt: 'A comprehensive guide to Machine-to-Machine authentication — from OAuth 2.0 Client Credentials to mTLS, JWTs, and API keys. Learn how to secure your microservices.',
    category: 'backend',
    content: '',
    author: 'Coder Secret',
    date: '2026-04-03',
    readTime: '11 min read',
    tags: ['Authentication', 'Security', 'OAuth', 'Microservices', 'Python'],
    coverImage: '',
  },
  {
    id: '6',
    title: 'SSO Demystified: A Practical Guide to SAML and OIDC',
    slug: 'sso-saml-oidc-practical-guide',
    popularRank: 3,
    excerpt: 'Understand how Single Sign-On works under the hood. Compare SAML and OpenID Connect, learn the authentication flows, and know when to use each protocol.',
    category: 'backend',
    content: '',
    author: 'Coder Secret',
    date: '2026-04-03',
    readTime: '14 min read',
    tags: ['SSO', 'SAML', 'OIDC', 'Authentication', 'Security'],
    coverImage: '',
  },
  {
    id: '5',
    title: 'Cron Jobs Explained: The Complete Guide with Real-World Examples',
    slug: 'cron-jobs-complete-guide-with-examples',
    popularRank: 2,
    excerpt: 'Everything you need to know about cron jobs — from basic syntax to advanced scheduling patterns. Packed with practical examples anyone can follow.',
    category: 'devops',
    content: '',
    author: 'Coder Secret',
    date: '2026-04-03',
    readTime: '12 min read',
    tags: ['Linux', 'DevOps', 'Cron', 'Automation', 'Tutorial'],
    coverImage: '',
  },
  {
    id: '4',
    title: 'DRF API Logger: Effortless API Logging for Django REST Framework',
    slug: 'drf-api-logger-django-rest-framework',
    excerpt: 'Discover how DRF API Logger makes it dead simple to capture, monitor, and profile every API call in your Django REST Framework application — with per-request latency breakdowns, N+1 query detection, CSV export, GZIP support, and zero impact on response times.',
    category: 'open-source',
    content: '',
    author: 'Vishal Anand',
    date: '2026-04-25',
    readTime: '8 min read',
    tags: ['Django', 'Python', 'DRF', 'API Logging', 'Open Source'],
    coverImage: '',
  }
];

// Content is loaded dynamically per-post from blog-content/<slug>.ts
// Auto-calculate readTime from content for all posts
BLOG_POSTS.forEach(post => {
  if (!post.readTime || post.readTime === '') {
    post.readTime = '5 min read';
  }
});
