// Generated by scripts/generate-course-directory.js. Contains no lesson bodies.
export const COURSE_LESSON_DIRECTORY = [
  {
    "slug": "mastering-spiffe-spire",
    "title": "Mastering SPIFFE & SPIRE: Zero Trust for Cloud Native Systems",
    "lessons": [
      {
        "slug": "understanding-zero-trust-security",
        "title": "Understanding Zero Trust Security"
      },
      {
        "slug": "cryptography-pki-foundations",
        "title": "Cryptography and PKI Foundations"
      },
      {
        "slug": "spiffe-fundamentals",
        "title": "SPIFFE Fundamentals"
      },
      {
        "slug": "spire-architecture-components",
        "title": "SPIRE Architecture and Components"
      },
      {
        "slug": "running-spire-on-kubernetes",
        "title": "Running SPIRE on Kubernetes"
      },
      {
        "slug": "working-with-svids-workload-api",
        "title": "Working with SVIDs and the Workload API"
      },
      {
        "slug": "authorization-policy-enforcement",
        "title": "Authorization and Policy Enforcement"
      },
      {
        "slug": "spire-integrations-service-mesh",
        "title": "SPIRE Integrations and Service Mesh"
      },
      {
        "slug": "advanced-spire-architectures",
        "title": "Advanced SPIRE Architectures"
      },
      {
        "slug": "day-two-operations-observability",
        "title": "Day Two Operations and Observability"
      },
      {
        "slug": "spiffe-spire-ecosystem",
        "title": "The SPIFFE/SPIRE Ecosystem"
      },
      {
        "slug": "building-zero-trust-platform",
        "title": "Building a Complete Zero Trust Platform"
      },
      {
        "slug": "spiffe-for-ai-infrastructure",
        "title": "SPIFFE for AI Infrastructure"
      }
    ]
  },
  {
    "slug": "cloud-native-security-engineering",
    "title": "Cloud Native Security Engineering: Securing Kubernetes, Workloads, APIs & Zero Trust Systems",
    "lessons": [
      {
        "slug": "introduction-cloud-native-security",
        "title": "Introduction to Cloud Native Security"
      },
      {
        "slug": "kubernetes-foundations-security",
        "title": "Kubernetes Foundations for Security"
      },
      {
        "slug": "containers-workload-security",
        "title": "Containers & Workload Security"
      },
      {
        "slug": "kubernetes-authentication-authorization",
        "title": "Kubernetes Authentication & Authorization"
      },
      {
        "slug": "zero-trust-security-fundamentals",
        "title": "Zero Trust Security Fundamentals"
      },
      {
        "slug": "spiffe-spire-deep-dive",
        "title": "SPIFFE & SPIRE Deep Dive"
      },
      {
        "slug": "service-mesh-security",
        "title": "Service Mesh Security"
      },
      {
        "slug": "policy-as-code-security",
        "title": "Policy-as-Code Security"
      },
      {
        "slug": "secrets-management-machine-identity",
        "title": "Secrets Management & Machine Identity"
      },
      {
        "slug": "runtime-security-threat-detection",
        "title": "Runtime Security & Threat Detection"
      },
      {
        "slug": "supply-chain-security",
        "title": "Cloud Native Supply Chain Security"
      },
      {
        "slug": "secure-cicd-pipelines",
        "title": "Secure CI/CD Pipelines"
      },
      {
        "slug": "observability-security-monitoring",
        "title": "Observability & Security Monitoring"
      },
      {
        "slug": "multi-cluster-multi-cloud-security",
        "title": "Multi-Cluster & Multi-Cloud Security"
      },
      {
        "slug": "ai-infrastructure-security",
        "title": "AI Infrastructure Security"
      },
      {
        "slug": "production-architecture-capstone",
        "title": "Production Architecture & Capstone"
      }
    ]
  },
  {
    "slug": "production-rag-systems-engineering",
    "title": "Production-Grade RAG Systems Engineering",
    "lessons": [
      {
        "slug": "introduction-ai-rag-systems",
        "title": "Introduction to AI & RAG Systems"
      },
      {
        "slug": "foundations-search-retrieval",
        "title": "Foundations of Search & Retrieval"
      },
      {
        "slug": "embeddings-deep-dive",
        "title": "Embeddings Deep Dive"
      },
      {
        "slug": "vector-databases-engineering",
        "title": "Vector Databases Engineering"
      },
      {
        "slug": "document-processing-chunking",
        "title": "Document Processing & Chunking"
      },
      {
        "slug": "building-basic-rag-systems",
        "title": "Building Basic RAG Systems"
      },
      {
        "slug": "advanced-retrieval-engineering",
        "title": "Advanced Retrieval Engineering"
      },
      {
        "slug": "ai-agents-agentic-rag",
        "title": "AI Agents & Agentic RAG"
      },
      {
        "slug": "production-rag-architecture",
        "title": "Production RAG Architecture"
      },
      {
        "slug": "rag-evaluation-quality-engineering",
        "title": "RAG Evaluation & Quality Engineering"
      },
      {
        "slug": "ai-observability-engineering",
        "title": "AI Observability Engineering"
      },
      {
        "slug": "security-rag-systems",
        "title": "Security for RAG Systems"
      },
      {
        "slug": "deploying-rag-systems",
        "title": "Deploying RAG Systems"
      },
      {
        "slug": "advanced-rag-architectures",
        "title": "Advanced RAG Architectures"
      },
      {
        "slug": "ai-infrastructure-future-systems",
        "title": "AI Infrastructure & Future Systems"
      },
      {
        "slug": "production-capstone-project",
        "title": "Production Capstone Project"
      }
    ]
  },
  {
    "slug": "distributed-systems-engineering",
    "title": "Distributed Systems Engineering: Building Scalable, Reliable & Secure Systems",
    "lessons": [
      {
        "slug": "foundations-distributed-systems",
        "title": "Foundations of Distributed Systems"
      },
      {
        "slug": "networking-distributed-communication",
        "title": "Networking & Distributed Communication"
      },
      {
        "slug": "event-driven-asynchronous-systems",
        "title": "Event-Driven & Asynchronous Systems"
      },
      {
        "slug": "distributed-data-management",
        "title": "Distributed Data Management"
      },
      {
        "slug": "consensus-coordination",
        "title": "Consensus & Coordination"
      },
      {
        "slug": "scalability-engineering",
        "title": "Scalability Engineering"
      },
      {
        "slug": "reliability-failure-engineering",
        "title": "Reliability & Failure Engineering"
      },
      {
        "slug": "distributed-security-zero-trust",
        "title": "Distributed Security & Zero Trust"
      },
      {
        "slug": "observability-debugging",
        "title": "Observability & Debugging"
      },
      {
        "slug": "kubernetes-cloud-native-distributed-systems",
        "title": "Kubernetes & Cloud Native Distributed Systems"
      },
      {
        "slug": "real-world-failure-scenarios",
        "title": "Real-World Failure Scenarios"
      },
      {
        "slug": "production-system-design-capstone",
        "title": "Production System Design & Capstone"
      }
    ]
  },
  {
    "slug": "centralized-authentication-authorization-envoy",
    "title": "Centralized Authentication and Authorization with Envoy",
    "lessons": [
      {
        "slug": "google-style-login-kubernetes-products",
        "title": "Google-Style Login for Many Kubernetes Products"
      },
      {
        "slug": "auth-vocabulary-sso-saml-oidc-jwt-jwks-tokens",
        "title": "Auth Vocabulary: SSO, SAML, OIDC, JWT, JWKS, and Tokens"
      },
      {
        "slug": "plain-envoy-central-front-door",
        "title": "Plain Envoy as the Central Front Door"
      },
      {
        "slug": "jwt-jwks-validation-envoy",
        "title": "JWT and JWKS Validation at Envoy"
      },
      {
        "slug": "sso-oidc-saml-envoy-external-auth",
        "title": "SSO with OIDC or SAML Through Envoy and External Auth"
      },
      {
        "slug": "access-service-tokens-federated-credentials",
        "title": "Access Tokens, Service Tokens, and Federated Credentials"
      },
      {
        "slug": "authorization-policy-headers-product-boundaries",
        "title": "Authorization Policy, Headers, and Product Boundaries"
      },
      {
        "slug": "production-design-security-performance-scale",
        "title": "Production Design: Security, Performance, and Scale"
      }
    ]
  },
  {
    "slug": "production-analytics-engineering-dbt",
    "title": "Production Analytics Engineering with dbt: Metrics, Semantic Layers & Lineage",
    "lessons": [
      {
        "slug": "what-is-analytics-engineering",
        "title": "What Analytics Engineering Actually Is"
      },
      {
        "slug": "tables-grain-dashboard-lies",
        "title": "Tables, Grain, and Why Dashboards Lie"
      },
      {
        "slug": "dbt-mental-model",
        "title": "The dbt Mental Model"
      },
      {
        "slug": "staging-models",
        "title": "Staging Models"
      },
      {
        "slug": "intermediate-models",
        "title": "Intermediate Models"
      },
      {
        "slug": "marts-facts-dimensions",
        "title": "Marts: Facts and Dimensions"
      },
      {
        "slug": "testing-data-quality",
        "title": "Testing and Data Quality"
      },
      {
        "slug": "freshness-contracts-documentation",
        "title": "Freshness, Contracts, and Documentation"
      },
      {
        "slug": "incremental-models-backfills",
        "title": "Incremental Models and Backfills"
      },
      {
        "slug": "metrics-as-product-apis",
        "title": "Metrics as Product APIs"
      },
      {
        "slug": "semantic-layer-fundamentals",
        "title": "Semantic Layer Fundamentals"
      },
      {
        "slug": "metricflow-dbt-semantic-layer",
        "title": "MetricFlow and the dbt Semantic Layer"
      },
      {
        "slug": "lineage-dbt-artifacts",
        "title": "Lineage with dbt Artifacts"
      },
      {
        "slug": "data-incidents-debugging",
        "title": "Data Incidents and Debugging"
      },
      {
        "slug": "analytics-engineering-cicd",
        "title": "CI/CD for Analytics Engineering"
      },
      {
        "slug": "trusted-analytics-layer-capstone",
        "title": "Capstone: Build a Trusted Analytics Layer"
      }
    ]
  },
  {
    "slug": "malware-analysis-defense",
    "title": "Malware Analysis and Defense for Developers",
    "lessons": [
      {
        "slug": "authorization-ethics-lab-containment",
        "title": "Authorization, Ethics, and Lab Containment"
      },
      {
        "slug": "malware-concepts-defender-taxonomy",
        "title": "Malware Concepts and Multi-Axis Taxonomy"
      },
      {
        "slug": "evidence-acquisition-provenance-chain-of-custody",
        "title": "Evidence Acquisition, Provenance, and Chain of Custody"
      },
      {
        "slug": "static-triage-modern-artifacts",
        "title": "Static Triage Across PE, ELF, Scripts, and Packages"
      },
      {
        "slug": "assembly-compiler-literacy",
        "title": "Assembly and Compiler Literacy"
      },
      {
        "slug": "ghidra-decompiler-workflow",
        "title": "Ghidra and Decompiler Workflow"
      },
      {
        "slug": "managed-code-packages-containers-wasm",
        "title": "Managed Code, Packages, Containers, and WASM"
      },
      {
        "slug": "controlled-endpoint-behavioral-analysis",
        "title": "Controlled Endpoint Behavioral Analysis"
      },
      {
        "slug": "offline-network-evidence",
        "title": "Offline Network Evidence"
      },
      {
        "slug": "sanitized-memory-volatile-evidence",
        "title": "Sanitized Memory and Volatile Evidence"
      },
      {
        "slug": "mitre-attack-d3fend-mapping",
        "title": "MITRE ATT&CK v19.2 and D3FEND Mapping"
      },
      {
        "slug": "yara-detection-as-code",
        "title": "YARA Detection as Code"
      },
      {
        "slug": "sigma-telemetry-analytics",
        "title": "Sigma and Telemetry Analytics"
      },
      {
        "slug": "containment-eradication-recovery",
        "title": "Containment, Eradication, and Recovery"
      },
      {
        "slug": "reporting-safe-intelligence-sharing",
        "title": "Reporting and Safe Intelligence Sharing"
      },
      {
        "slug": "building-malware-resistant-software",
        "title": "Building Malware-Resistant Software"
      },
      {
        "slug": "capstone-synthetic-developer-tool-incident",
        "title": "Capstone: The Northstar Developer Tool Incident"
      }
    ]
  }
] as const;
