import { Component, inject } from '@angular/core';
import { SlidePlayerComponent, SlideData } from '../../components/slide-player/slide-player';
import { DRF_API_LOGGER_ANALYTICS_ID } from '../../services/analytics.service';
import { SeoService } from '../../services/seo.service';

@Component({
  selector: 'app-drf-api-logger-slides',
  standalone: true,
  imports: [SlidePlayerComponent],
  template: `
    <app-slide-player
      [slides]="slides"
      deckTitle="DRF API Logger 1.4"
      backUrl="/blog/drf-api-logger-django-rest-framework"
      [analyticsId]="analyticsId" />
  `,
})
export class DrfApiLoggerSlidesComponent {
  private seo = inject(SeoService);

  readonly analyticsId = DRF_API_LOGGER_ANALYTICS_ID;

  slides: SlideData[] = [
    {
      type: 'title',
      title: 'DRF API Logger 1.4',
      subtitle: 'A maintainer-led walkthrough of safe request logging, sampled profiling, correlation, and production operations for Django REST Framework.',
      tags: ['24 SLIDES', 'PRODUCTION GUIDE', 'DJANGO · DRF'],
      narration: 'Welcome. I am Vishal Anand, the creator and maintainer of DRF API Logger. This walkthrough covers version 1.4 and focuses on what the package does, where its limits are, and how to operate it safely.',
    },
    {
      type: 'grid',
      eyebrow: '01 · Verified baseline',
      title: 'What this deck covers',
      body: 'Version and compatibility claims are current as of this release, and every resource is linked at the end.',
      items: [
        { title: 'Version 1.4.0', desc: 'Released July 8, 2026 on PyPI.' },
        { title: 'Supported stack', desc: 'Python 3.10+, Django 4.2+, and DRF 3.16+.' },
        { title: 'Apache-2.0', desc: 'The package is free and open source under Apache-2.0.' },
        { title: 'DRF documentation', desc: "Listed in DRF's official third-party packages documentation; not endorsed, certified, or maintained by DRF." },
      ],
      narration: 'Start with the verifiable baseline. This deck covers 1.4.0, released on July eighth, 2026. The supported baseline is Python 3.10, Django 4.2, and DRF 3.16 or newer. The package uses Apache-2.0 and appears in the official DRF third-party package documentation, which is a listing rather than an endorsement.',
    },
    {
      type: 'grid',
      eyebrow: '01 · Purpose',
      title: 'Why keep structured API records?',
      items: [
        { title: 'Reproduce failures', desc: 'Inspect an eligible request, its response, status, and server execution time.' },
        { title: 'Find bottlenecks', desc: 'Use sampled profiling to investigate slow SQL, N+1 patterns, middleware, or application work.' },
        { title: 'Support investigations', desc: 'Keep bounded operational evidence without claiming an immutable audit trail.' },
        { title: 'Understand patterns', desc: 'Filter captured calls by endpoint, method, status, date, and performance.' },
      ],
      narration: 'Structured API records help with failure reproduction, performance investigation, support work, and usage patterns. They are operational evidence. They are not an immutable audit log or a compliance guarantee.',
    },
    {
      type: 'content',
      eyebrow: '01 · Architecture',
      title: 'Low overhead does not mean zero overhead',
      body: 'The middleware observes an eligible request and response, prepares the record, and enqueues it. A background worker batches database writes.',
      bullets: [
        'Capture, masking, serialization, custom handling, and enqueueing remain on the request path',
        'The background worker performs batched database writes instead of one insert per request',
        'Signal listeners and profiling still need workload testing and bounded execution',
      ],
      narration: 'The performance boundary matters. Database writes are batched in the background, but capture, masking, serialization, custom handling, and enqueueing still happen on the request path. Call this low request-path overhead, not zero overhead.',
    },
    {
      type: 'content',
      eyebrow: '01 · Runtime model',
      title: 'Sync, ASGI, and request-scoped context',
      body: "Version 1.4 supports Django's async middleware chain while remaining compatible with synchronous deployments.",
      bullets: [
        'ASGI-native middleware keeps concurrent request context isolated',
        'Correlation can parse X-Request-ID, X-Correlation-ID, traceparent, and X-Trace-ID',
        'Optional logging context exposes correlation metadata during the view call',
      ],
      narration: 'The modern middleware works with the async Django chain as well as synchronous deployments. Correlation metadata is isolated per request and can be exposed to application logging during the view call.',
    },
    {
      type: 'content',
      eyebrow: '02 · Setup',
      title: 'Supported prerequisites',
      bullets: [
        'Python 3.10 or newer',
        'Django 4.2 or newer',
        'Django REST Framework 3.16 or newer',
        'An existing DRF project with a reviewed logging and retention policy',
      ],
      body: 'Use the tested support range for new deployments; compatibility claims from older releases no longer describe version 1.4.',
      narration: 'For version 1.4, start with Python 3.10, Django 4.2, and DRF 3.16 or newer. Older compatibility claims belong to older releases and should not drive a new deployment.',
    },
    {
      type: 'code',
      eyebrow: '02 · Setup · Step 1',
      title: 'Install the current package',
      body: 'Install from PyPI, then lock the resolved version through your normal dependency workflow.',
      code: '$ pip install drf-api-logger\n\n# Verify the installed version in your environment\n$ python -m pip show drf-api-logger',
      lang: 'terminal',
      narration: 'Install the package from PyPI. Let your dependency manager record the resolved version, and verify the installed package in the environment you will deploy.',
    },
    {
      type: 'code',
      eyebrow: '02 · Setup · Step 2',
      title: 'Register the Django app',
      body: 'Register the app so Django can discover its model, migrations, admin, checks, and management commands.',
      code: "INSTALLED_APPS = [\n    # ... Django and project apps\n    'rest_framework',\n    'drf_api_logger',\n]",
      lang: 'settings.py',
      narration: 'Add drf_api_logger to installed apps. This lets Django discover the model, migrations, admin integration, checks, and management commands.',
    },
    {
      type: 'code',
      eyebrow: '02 · Setup · Step 3',
      title: 'Add middleware and choose a destination',
      body: 'Database and signal destinations are opt-in. Enable only the path you plan to operate.',
      code: "MIDDLEWARE = [\n    # ... reviewed middleware order\n    'drf_api_logger.middleware.api_logger_middleware.APILoggerMiddleware',\n]\n\nDRF_API_LOGGER_DATABASE = True\nDRF_API_LOGGER_SIGNAL = False",
      lang: 'settings.py',
      narration: 'Add the API logger middleware in a reviewed order, then explicitly enable database logging, signal logging, or both. Neither destination should be treated as a substitute for a retention and access policy.',
    },
    {
      type: 'code',
      eyebrow: '02 · Setup · Step 4',
      title: 'Inspect, migrate, and run diagnostics',
      body: 'Treat an upgrade on a large MySQL or MariaDB log table as a production schema change.',
      code: '$ python manage.py sqlmigrate drf_api_logger 0003\n$ python manage.py migrate\n$ python manage.py drf_api_logger_doctor',
      lang: 'terminal',
      narration: 'Inspect migration 0003 before changing a large MySQL or MariaDB table because adding profiling columns may lock or rebuild it. Test the generated SQL for your exact database, migrate through an approved process, and run the read-only doctor command before deployment.',
    },
    {
      type: 'grid',
      eyebrow: '03 · Destinations',
      title: 'Database, signal, or both',
      body: 'Filters and endpoint policy decide which calls are eligible before you retain or export them.',
      items: [
        { title: 'Database', desc: 'Django admin search, filters, charts, CSV export, slow markers, and profiling diagnosis.' },
        { title: 'Signal', desc: 'An integration point for an application-owned log pipeline, alert, or custom consumer.' },
        { title: 'Both', desc: 'A short local debugging window plus a deliberately minimized external event stream.' },
        { title: 'Neither by default', desc: 'Choose and operate a destination explicitly; do not collect data without a purpose.' },
      ],
      narration: 'Database mode provides the admin experience. Signal mode hands an eligible event to code you own. You can use both, but filters, minimization, and retention should be explicit before production traffic arrives.',
    },
    {
      type: 'code',
      eyebrow: '03 · Safe defaults',
      title: 'Mask secrets and bound payloads',
      body: 'The defaults cap stored request bodies at 32 KiB and response bodies at 64 KiB. A value of minus one is unlimited.',
      code: "DRF_API_LOGGER_EXCLUDE_KEYS = [\n    'password', 'token', 'access', 'refresh',\n    'secret', 'api_key', 'authorization',\n]\n\nDRF_API_LOGGER_MAX_REQUEST_BODY_SIZE = 32768\nDRF_API_LOGGER_MAX_RESPONSE_BODY_SIZE = 65536\n# -1 removes the corresponding limit",
      lang: 'settings.py',
      narration: 'Extend masking with domain-specific credential and personal data keys. The documented defaults cap requests at 32,768 bytes and responses at 65,536 bytes. Minus one means unlimited, so use it only after a storage and privacy review.',
    },
    {
      type: 'image',
      eyebrow: '03 · Admin',
      title: 'Admin analytics overview',
      caption: 'Charts summarize captured API activity and load on demand so routine log browsing stays focused.',
      src: '/images/drf-api-logger/01-admin-dashboard-960.webp',
      imageWidth: 960,
      imageHeight: 600,
      narration: 'The admin overview summarizes captured traffic. Charts load on demand, which keeps the routine list view focused while still making volume and status patterns available for investigation.',
    },
    {
      type: 'image',
      eyebrow: '03 · Admin',
      title: 'Search and filter captured calls',
      caption: 'The list view exposes method, status, execution time, SQL query count, filters, and search for eligible records.',
      src: '/images/drf-api-logger/02-api-logs-list-960.webp',
      imageWidth: 960,
      imageHeight: 1493,
      narration: 'The list view lets an operator narrow captured records by method, status, date, speed, and profiling fields. Access to this page should be restricted because request and response evidence may remain sensitive even after masking.',
    },
    {
      type: 'image',
      eyebrow: '04 · Profiling',
      title: 'Investigate a slow SQL request',
      caption: 'The detail view separates SQL, middleware, and application time so a slow request has a concrete starting point.',
      src: '/images/drf-api-logger/03-api-log-detail-slow-sql-960.webp',
      imageWidth: 960,
      imageHeight: 1060,
      narration: 'A profiling detail view breaks down where server execution time went. A slow-SQL diagnosis is an investigation hint, so confirm it with the query plan, indexes, and a representative workload.',
    },
    {
      type: 'image',
      eyebrow: '05 · Privacy',
      title: 'Verify masking before production',
      caption: 'The detail view shows credential-like fields replaced before storage; add your own domain-specific keys and test nested payloads.',
      src: '/images/drf-api-logger/04-api-log-detail-login-masked-960.webp',
      imageWidth: 960,
      imageHeight: 1061,
      narration: 'Masking covers common credential keys and headers, and you can extend it. Validate realistic nested request and response examples before production because a generic default cannot know every sensitive field in your domain.',
    },
    {
      type: 'image',
      eyebrow: '04 · Profiling',
      title: 'Use N+1 detection as a lead',
      caption: 'High SQL time and query count can point to an N+1 pattern; confirm the diagnosis before changing code.',
      src: '/images/drf-api-logger/05-api-log-detail-n-plus-one-960.webp',
      imageWidth: 960,
      imageHeight: 1105,
      narration: 'High SQL percentage plus many queries can suggest an N plus one pattern. Treat that label as a lead, then inspect query repetition and the ORM access pattern before selecting prefetching, joins, or another fix.',
    },
    {
      type: 'code',
      eyebrow: '04 · Profiling',
      title: 'Profile a sample, not by habit',
      body: 'Normal logging policy still applies; the sample rate controls which logged requests receive the extra profiling breakdown.',
      code: 'DRF_API_LOGGER_ENABLE_PROFILING = True\nDRF_API_LOGGER_PROFILING_SQL_TRACKING = True\nDRF_API_LOGGER_PROFILING_SAMPLE_RATE = 0.10',
      lang: 'settings.py',
      narration: 'Profiling is opt-in. On a busy system, use a fraction between zero and one to profile a sample of logged requests. Validate SQL tracking overhead in staging and monitor the production result.',
    },
    {
      type: 'code',
      eyebrow: '05 · Data policy',
      title: 'Apply endpoint policy before export',
      body: 'Policies can skip a route, remove bodies, add mask keys, or suppress its signal. A custom handler can transform or drop a record before queueing.',
      code: "DRF_API_LOGGER_POLICY = {\n    'rules': [\n        {'url_name': 'health_check', 'log': False},\n        {\n            'route': 'api/payments/',\n            'request_body': False,\n            'response_body': False,\n            'mask_keys': ['card_number', 'payment_token'],\n            'signal': False,\n        },\n    ],\n}\n\nDRF_API_LOGGER_CUSTOM_HANDLER = 'myapp.logging.clean_api_log'",
      lang: 'settings.py',
      narration: 'Use endpoint policy when one route needs stricter collection or export rules. A custom handler can transform data or return none to drop a record, but keep it fast because it executes on the request path.',
    },
    {
      type: 'code',
      eyebrow: '06 · Correlation',
      title: 'Reuse upstream request and trace context',
      body: 'Correlation metadata is available during the request and in signal payloads; it is intentionally not added to the log model schema.',
      code: "DRF_API_LOGGER_ENABLE_CORRELATION = True\nDRF_API_LOGGER_CORRELATION_REQUEST_ID_HEADERS = [\n    'X-Request-ID', 'X-Correlation-ID',\n]\nDRF_API_LOGGER_CORRELATION_TRACE_ID_HEADERS = [\n    'traceparent', 'X-Trace-ID',\n]\nDRF_API_LOGGER_ENABLE_LOGGING_CONTEXT = True",
      lang: 'settings.py',
      narration: 'Correlation can reuse gateway request IDs and W3C traceparent data. Logging context makes that metadata available during the view call. Put high-cardinality IDs in logs and traces, never in metric labels.',
    },
    {
      type: 'code',
      eyebrow: '06 · Integrations',
      title: 'Add context to tools you already run',
      body: 'The helpers do not install or configure Prometheus, OpenTelemetry, or Sentry; your application owns those dependencies and exporters.',
      code: "from drf_api_logger import API_LOGGER_SIGNAL\nfrom drf_api_logger.observability import (\n    annotate_opentelemetry_span,\n    configure_sentry_scope,\n    record_prometheus_metrics,\n)\n\ndef export_observability(**event):\n    record_prometheus_metrics(event, API_REQUESTS, API_DURATION)\n    annotate_opentelemetry_span(current_span, event)\n    configure_sentry_scope(sentry_scope, event)\n\nAPI_LOGGER_SIGNAL.listen += export_observability",
      lang: 'python',
      narration: 'Optional helpers can record safe Prometheus labels, annotate an active OpenTelemetry span, or configure Sentry context. They are adapters, not observability backends, and the application still owns dependencies, exporters, sampling, and retention.',
    },
    {
      type: 'code',
      eyebrow: '06 · Metrics and detection',
      title: 'Measure logger health; detect, do not block',
      body: 'Logger and pipeline metrics are separate from optional API metrics. Security signals are disabled by default and only report suspicious patterns.',
      code: "DRF_API_LOGGER_METRICS_ENABLED = True\nDRF_API_LOGGER_METRICS_GROUPS = ['logger', 'pipeline']\nDRF_API_LOGGER_API_METRICS_ENABLED = True\n\n# Optional detect-only signals\nDRF_API_LOGGER_SECURITY_METRICS_ENABLED = True\nDRF_API_LOGGER_SECURITY_MODE = 'detect'",
      lang: 'settings.py',
      narration: 'First-party metrics can expose request overhead, queue and worker health, flushes, storage failures, and optional API timing. Security signals are detect-only. They do not block attacks and do not replace a WAF, IDS, SIEM, or investigation process. Protect any Prometheus endpoint on an internal authenticated route.',
    },
    {
      type: 'grid',
      eyebrow: '07 · Operate it',
      title: 'Production release checklist',
      body: 'A logger is useful only when collection, access, health, and deletion are all operated deliberately.',
      items: [
        { title: 'Diagnose first', desc: 'Run python manage.py drf_api_logger_doctor before deployment.' },
        { title: 'Prune safely', desc: 'Preview with prune_api_logs --days 30 --dry-run, then delete in bounded batches.' },
        { title: 'Measure overhead', desc: 'Benchmark capture, masking, enqueue, profiling, and custom handlers with representative traffic.' },
        { title: 'Control access', desc: 'Restrict admin, metrics, database, and exported logs as sensitive production data.' },
        { title: 'Watch health', desc: 'Alert on queue depth, worker state, dropped records, flush duration, and storage failures.' },
        { title: 'Keep the boundary', desc: 'Not an immutable audit trail, compliance guarantee, WAF, SIEM, IDS, APM, or tracing backend.' },
      ],
      narration: 'Before release, run the doctor, preview retention deletion, benchmark representative traffic, restrict access, monitor the logging pipeline, and keep the product boundary clear. Production safety comes from the whole operating process, not one package setting.',
    },
    {
      type: 'end',
      title: 'Verify, install, and operate deliberately.',
      subtitle: 'Open the primary resources or copy the install command. Return to the article for the complete configuration and trade-off guide.',
      links: [
        {
          label: 'FULL GUIDE',
          value: 'Configuration and trade-offs',
          href: '/blog/drf-api-logger-django-rest-framework',
          ariaLabel: 'Read the complete DRF API Logger guide',
          analyticsDestination: 'article',
        },
        {
          label: 'PYPI',
          value: 'Version 1.4.0',
          href: 'https://pypi.org/project/drf-api-logger/',
          external: true,
          ariaLabel: 'Open DRF API Logger on PyPI',
          analyticsResource: 'pypi',
        },
        {
          label: 'DOCUMENTATION',
          value: 'ReadTheDocs · 1.4',
          href: 'https://drf-api-logger.readthedocs.io/en/latest/',
          external: true,
          ariaLabel: 'Open the DRF API Logger documentation',
          analyticsResource: 'docs',
        },
        {
          label: 'GITHUB',
          value: 'Source and releases',
          href: 'https://github.com/vishalanandl177/DRF-API-Logger',
          external: true,
          ariaLabel: 'Open the DRF API Logger GitHub repository',
          analyticsResource: 'github',
        },
        {
          label: 'ISSUES',
          value: 'Report or request',
          href: 'https://github.com/vishalanandl177/DRF-API-Logger/issues',
          external: true,
          ariaLabel: 'Open DRF API Logger issues on GitHub',
          analyticsResource: 'issues',
        },
        {
          label: 'DRF LISTING',
          value: 'Third-party packages',
          href: 'https://www.django-rest-framework.org/community/third-party-packages/',
          external: true,
          ariaLabel: "Open Django REST Framework's third-party packages documentation",
          analyticsResource: 'official-listing',
        },
        {
          label: 'INSTALL',
          value: 'pip install drf-api-logger',
          copyValue: 'pip install drf-api-logger',
          ariaLabel: 'Copy the DRF API Logger install command',
          analyticsAction: 'install',
        },
      ],
      narration: 'You now have the supported baseline, the request-path performance boundary, safe configuration, current observability features, and an operations checklist. Use the primary links to verify the release, read the full documentation, inspect the source, or report an issue.',
    },
  ];

  constructor() {
    this.seo.update({
      title: 'DRF API Logger 1.4 - Interactive Production Guide',
      description: 'Learn DRF API Logger 1.4 through 24 interactive slides covering safe request logging, sampled profiling, correlation, metrics, security signals, and production operations.',
      url: '/slides/drf-api-logger',
      robots: 'noindex,follow',
      jsonLd: {
        '@context': 'https://schema.org',
        '@type': 'LearningResource',
        name: 'DRF API Logger 1.4 Interactive Production Guide',
        description: 'A 24-slide maintainer-led guide to safe request logging, sampled profiling, correlation, metrics, detect-only security signals, and production operations for Django REST Framework.',
        url: 'https://coderssecret.com/slides/drf-api-logger',
        inLanguage: 'en',
        learningResourceType: 'Slide deck',
        educationalLevel: 'Intermediate',
        isAccessibleForFree: true,
        isBasedOn: 'https://coderssecret.com/blog/drf-api-logger-django-rest-framework',
      },
    });
  }
}
